"""Render the repository's specialist-skill index from SKILL.md frontmatter."""
from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "references" / "skills.md"


def _frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    header = text.split("---\n", 2)[1]
    name = re.search(r"^name:\s*(.+)$", header, re.M)
    description = re.search(r"^description:\s*(.+)$", header, re.M)
    if name is None or description is None:
        raise ValueError(f"{path}: missing name or description")
    value = description.group(1).strip()
    if value in {">", ">-", "|", "|-"}:
        start = description.end()
        lines = []
        for line in header[start:].splitlines():
            if line and not line.startswith((" ", "\t")):
                break
            if line.strip():
                lines.append(line.strip())
        value = " ".join(lines)
    return {"name": name.group(1).strip(), "description": value}


def render() -> str:
    skills = []
    for path in sorted((ROOT / "skills").glob("*/SKILL.md")):
        item = _frontmatter(path)
        item["path"] = path.parent.relative_to(ROOT).as_posix() + "/"
        skills.append(item)
    lines = [
        "# Specialist skill catalog",
        "",
        "Generated from `skills/*/SKILL.md`. Do not edit this file by hand; run `python scripts/generate_skill_catalog.py --write`.",
        "",
        f"Available specialist skills: **{len(skills)}**.",
        "",
        "| Skill | Purpose |",
        "|---|---|",
    ]
    for item in skills:
        description = item["description"].replace("|", "\\|")
        lines.append(f"| [`{item['name']}`](../{item['path']}) | {description} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    if args.write:
        args.output.write_text(rendered, encoding="utf-8")
    if args.check and current != rendered:
        print("skill catalog is stale; run python scripts/generate_skill_catalog.py --write")
        return 1
    if not args.write and not args.check:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
