"""Import a DFTK capability manifest and render the Skill capability catalog."""
from __future__ import annotations

import argparse
import json
import shutil
from collections import defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "references" / "capabilities.manifest.json"
DEFAULT_CATALOG = ROOT / "references" / "capabilities.md"


def _parameter_rows(tool: dict[str, Any]) -> list[str]:
    properties = tool.get("parameters", {}).get("properties", {})
    if not properties:
        return ["No parameters.", ""]
    required = set(tool.get("parameters", {}).get("required", []))
    rows = ["| Name | Type | Required | Default |", "|---|---|---|---|"]
    for name, spec in properties.items():
        default = spec.get("default", "")
        if isinstance(default, (dict, list)):
            default = json.dumps(default, ensure_ascii=False)
        rows.append(f"| `{name}` | {spec.get('type', 'any')} | {'yes' if name in required else 'no'} | {default} |")
    return rows + [""]


def render_catalog(manifest: dict[str, Any]) -> str:
    tools = manifest.get("tools")
    if not isinstance(tools, list):
        raise ValueError("manifest has no tools list")
    if manifest.get("tool_count") != len(tools):
        raise ValueError("manifest tool_count does not match tools")

    lines = [
        f"# DFTK {manifest['toolkit_version']} capability catalog",
        "",
        "Generated from `references/capabilities.manifest.json`. Do not edit this file by hand; run `python scripts/sync_capabilities.py --write` after importing the matching DFTK manifest.",
        "",
        f"Schema: `{manifest['schema_version']}` · Tools: **{manifest['tool_count']}** · Safety: "
        + ", ".join(f"{level}={count}" for level, count in manifest.get("safety_counts", {}).items()),
        "",
        "## Domains",
        "",
    ]
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for tool in tools:
        grouped[tool["name"].split(".", 1)[0]].append(tool)
    for domain in sorted(grouped):
        lines.append(f"- `{domain}` — {len(grouped[domain])} capabilities")
    lines.append("")

    for domain in sorted(grouped):
        lines.extend([f"## {domain}", ""])
        for tool in sorted(grouped[domain], key=lambda item: item["name"]):
            lines.extend([f"### `{tool['name']}`", "", tool["description"], ""])
            details = [f"Safety: `{tool['safety']}`", f"Network: `{'yes' if tool.get('network') else 'no'}`"]
            if tool.get("requires"):
                details.append("Requires: " + ", ".join(f"`{item}`" for item in tool["requires"]))
            lines.extend([" · ".join(details), "", "#### Parameters", ""])
            lines.extend(_parameter_rows(tool))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--import-manifest", type=Path, metavar="PATH", help="copy a manifest from DFTK into this repository")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--write", action="store_true", help="write the rendered catalog")
    parser.add_argument("--check", action="store_true", help="fail when the catalog differs from the manifest")
    args = parser.parse_args()

    if args.import_manifest:
        args.manifest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(args.import_manifest, args.manifest)
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    rendered = render_catalog(manifest)
    existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    if args.write:
        args.output.write_text(rendered, encoding="utf-8")
    if args.check and existing != rendered:
        print("capability catalog is stale; run python scripts/sync_capabilities.py --write")
        return 1
    if not args.write and not args.check:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
